### ISSUE TITLE
Does not work with Test::MockFile

### ISSUE THREAD

**Issue by EvanCarroll** [cpanel/Overload-FileCheck#16]
The following test,

```
use Overload::FileCheck ();

# runs fine without this.
use Test::MockFile ();

Overload::FileCheck::mock_all_file_checks( sub {
    return Overload::FileCheck::FALLBACK_TO_REAL_OP();
} );

-e '/foo';
```

Will produce the somewhat cryptic error,

    -A is already mocked by Overload::FileCheck

**Comment by atoomic** [comment]
Test::MockFile uses Overload::FileCheck under the hood...
Test::MockFile by design mocks all -X check using Overload::FileCheck.

You cannot mock -X a second time when using Test::MockFile.
IMO you should use one or the other.

Closing this case by design

**Comment by EvanCarroll** [comment]
@atoomic So if a test is using `Test::MockFile` and we need to mock a file-exists test on a touchfile, we have to rewrite the whole test to use `Overload::FileCheck`?

**Comment by atoomic** [comment]
no I would say just use Test::MockFile API to mock the file as existing or not when using Test::MockFile and you have the -X checks mocked for you

**Comment by toddr** [comment]
Create the file in Test::Mock file and you've effectively done what you want. You either should be using Test::MockFile in a test file or Overload::FileCheck. NEVER both.
