### ISSUE TITLE
Update tests for passing TODOs

### ISSUE THREAD

**Issue by xsawyerx** [cpanel/Overload-FileCheck#19]
When running `make test`:

```
Test Summary Report
-------------------
t/mock-all-from-stat_advanced.t (Wstat: 0 Tests: 619 Failed: 0)
  TODO passed:   7, 88, 115, 121, 169, 196, 250, 302, 308
                329, 335, 459, 465, 486, 513, 540, 567
                594
```

**Comment by atoomic** [comment]
If you run the tests on multiple distro, you would realized that many of them are failing.
This is very distro dependent. If we consider removing the TODO we need to be very careful and add OS restrictions

**Comment by xsawyerx** [comment]
I see! Closing this issue.
